### ISSUE TITLE
Add a unique constraint on posts.(discussion_id, created_at)

### ISSUE THREAD

**Issue by nedrocks** [nedrocks/delphisbe#30]
This will allow us to ensure our paging will work and not have edge cases of exact same point in time creation. Highly unlikely but a good thing to protect against.

We will also have to have retry logic built into the code to retry on a constraint issue.

**Comment by jasondellaluce** [comment]
Should be solved by #31.

**Comment by nedrocks** [comment]
This is complete with #31
